### ISSUE TITLE
Pull from iPhone not appearing to work / null "options" array in Python code

### ISSUE THREAD

**Issue by trinitronx** [roznet/remotestash#4]
Testing this out from Linux to iPhone appears to work fine.  However, when I try to go the other way: iPhone -> Linux, the Python code throws an exception:

_**Note:**  Usernames, IPs and UUID scrubbed for privacy_

```
 ~/bin/remotestash pull  -v  -n testPhone
Skipping Service exampleuser RemoteStash._remotestash._tcp.local. on 192.168.1.10:60143
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Service exampleuser RemoteStash._remotestash._tcp.local. updated
Found Service testPhone RemoteStash._remotestash._tcp.local. added, running pull on 192.168.1.11:56030 {'uuid': 'ABCDEF01-0123-4567-89AB-CDEF01020304', 'temporary': 'yes'}
starting GET https://192.168.1.11:56030/pull
Exception in thread zeroconf-ServiceBrowser__remotestash._tcp.local.:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/zeroconf/__init__.py", line 1483, in run
    handler(self.zc)
  File "/usr/lib/python3/dist-packages/zeroconf/__init__.py", line 1422, in <lambda>
    lambda zeroconf: self._service_state_changed.fire(
  File "/usr/lib/python3/dist-packages/zeroconf/__init__.py", line 1301, in fire
    h(**kwargs)
  File "/usr/lib/python3/dist-packages/zeroconf/__init__.py", line 1395, in on_change
    listener.add_service(*args)
  File "/home/exampleuser/bin/remotestash", line 514, in add_service
    getattr(self,self.cmd)()
  File "/home/exampleuser/bin/remotestash", line 590, in pull
    item = self.item_from_response( response )
  File "/home/exampleuser/bin/remotestash", line 527, in item_from_response
    info = RemoteStashItem.info_from_headers(response.headers)
  File "/home/exampleuser/bin/remotestash", line 164, in info_from_headers
    info['encoding'] = options['charset']
NameError: name 'options' is not defined

Failed to find a stash on the local network
```

Line 164 in the code appears to be referencing an [undefined dict / map / hash named "`options`" here][1].  Assuming this was supposed to be pulled from `Content-Type` headers, I hardcoded this to `utf-8` instead of referencing the undefined `options['charset']` dict key.  After this monkey patch, it works!

Not sure where `options` was supposed to be set or how it was intended to parse from this header, so I don't have a pull request to fix this one yet without asking first how this was supposed to work.

[1]: https://github.com/roznet/remotestash/blob/master/bin/remotestash#L164

**Comment by roznet** [comment]
thanks for the feedback, sorry about the mistake, fixed now
